### ISSUE TITLE
ENH: improve type stability

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/BasisMatrices.jl#17]
<a href="https://github.com/spencerlyon2"><img src="https://avatars.githubusercontent.com/u/1001948?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [spencerlyon2](https://github.com/spencerlyon2)**
_Thursday Aug 06, 2015 at 21:23 GMT_
_Originally opened as https://github.com/QuantEcon/CompEcon.jl/issues/13_

---

There is a lot of flexibility in how we allow users to construct/evaluate a Basis/BasisStructure ect.

This comes at a cost.

We really should try to specialize more on input types and clean things up...

A quick look at `@code_warntype` for most of our methods reveals the current status.

**Comment by spencerlyon2** [comment]
<a href="https://github.com/spencerlyon2"><img src="https://avatars.githubusercontent.com/u/1001948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spencerlyon2](https://github.com/spencerlyon2)**
_Friday Aug 14, 2015 at 14:04 GMT_

----

One thing we might do here is instead of storing the `basisfamily`, `params`, `vals` as vectors, we could store them as tuples and have the tuple type be a type parameter. Then all field types will be concrete and we will get specialized code for all possible combinations of basis families
